test_ssl::test_servers_disconnect_when_changing_tls_config is updated (v02)
Under debugger cc1 can become ZERO.

utils.wait_until was updated to support manual (step by step) debugging.

---
Known problems

1) When cc1 become to ZERO this test fails at the check:

with bouncer.log_contains(
    r"pTxnPool.*database configuration changed|pTxnPool.*obsolete connection", 1
)

/home/dima/MY/Work/CurrentTasks/2025/PGBOUNCER/2025_03_26/PgBouncer/work03a/test/utils.py:1233: in log_contains
    assert match_count == times
E   AssertionError
....
match_count = 0
....
=========================== short test summary info ============================
FAILED test/test_ssl.py::test_servers_disconnect_when_changing_tls_config - AssertionError
=================== 1 failed, 4 warnings in 65.15s (0:01:05) ===================